on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download submodules
        run: |
          git submodule update --init --recursive

      - name: npm install, build
        run: |
          npm clean-install
          npm run build

      - name: Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit, Push
        run: |
          git --work-tree dist add --all # dist 폴더를 git root directory 로
          git commit -m 'Deploy by Github actions'
          git push origin HEAD:release --force
